services:
  db:
    image: postgres:latest
    container_name: vt_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://app:pass@db:5432/app?schema=public
      PORT: 3000
      NODE_ENV: development
    ports:
      - "3000:3000"

volumes:
  pgdata:
